##
##############################################################################
#
# @file       overosyncstats.py
# @author     The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010.
# @brief      Implementation of the OveroSyncStats object. This file has been
#             automatically generated by the UAVObjectGenerator. For use with
#             the PyMite VM of the FlightPlan module.
#
# @note       Object definition file: overosyncstats.xml.
#             This is an automatically generated file.
#             DO NOT modify manually.
#
# @see        The GNU Public License (GPL) Version 3
#
#############################################################################/
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#

from openpilot.uavtalk.uavobject import *

# Field Send definition
class SendField(UAVObjectField):
    def __init__(self):
    	UAVObjectField.__init__(self, 5, 1)

# Field Received definition
class ReceivedField(UAVObjectField):
    def __init__(self):
    	UAVObjectField.__init__(self, 5, 1)

# Field FramesyncErrors definition
class FramesyncErrorsField(UAVObjectField):
    def __init__(self):
    	UAVObjectField.__init__(self, 5, 1)

# Field UnderrunErrors definition
class UnderrunErrorsField(UAVObjectField):
    def __init__(self):
    	UAVObjectField.__init__(self, 5, 1)

# Field DroppedUpdates definition
class DroppedUpdatesField(UAVObjectField):
    def __init__(self):
    	UAVObjectField.__init__(self, 5, 1)

# Field Packets definition
class PacketsField(UAVObjectField):
    def __init__(self):
    	UAVObjectField.__init__(self, 5, 1)

# Field Connected definition
class ConnectedField(UAVObjectField):
    # Enumeration options
    FALSE = 0
    TRUE = 1
    def __init__(self):
    	UAVObjectField.__init__(self, 7, 1)



# Object OveroSyncStats definition
class OveroSyncStats(UAVObject):
    # Object constants
    OBJID = -771203156

    # Constructor
    def __init__(self):
        UAVObject.__init__(self, OveroSyncStats.OBJID)

        # Create object fields
    	self.Send = SendField()
    	self.addField(self.Send)
    	self.Received = ReceivedField()
    	self.addField(self.Received)
    	self.FramesyncErrors = FramesyncErrorsField()
    	self.addField(self.FramesyncErrors)
    	self.UnderrunErrors = UnderrunErrorsField()
    	self.addField(self.UnderrunErrors)
    	self.DroppedUpdates = DroppedUpdatesField()
    	self.addField(self.DroppedUpdates)
    	self.Packets = PacketsField()
    	self.addField(self.Packets)
    	self.Connected = ConnectedField()
    	self.addField(self.Connected)

        # Read field data
        self.read()
        self.metadata.read()
